# This config is not used. It's just an example.
#
version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/go:1.15
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: go build ./...
  test:
    docker:
      - image: circleci/go:1.15
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: go test -race ./...

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
